// build.js — FigJam plugin asset bundler
// Run `node build.js` to regenerate code.js

const fs = require('fs');
const path = require('path');

console.log('Reading findings-data.js...');
const findingsData = require('./findings-data.js');

console.log('Reading template.js...');
const templateSource = fs.readFileSync('./template.js', 'utf8');

// ── Collect all image entries ──────────────────────────────────────────────
const imageEntries = [
  ...(findingsData.boardScreenshots || []),
  ...(findingsData.appFrames || []),
  ...(findingsData.inventoryFrames || []),
];

// ── Base64-encode each image ───────────────────────────────────────────────
const images = {};
for (const entry of imageEntries) {
  const absPath = path.join(__dirname, '..', entry.path);
  console.log(`  Reading image: ${entry.path}`);
  if (!fs.existsSync(absPath)) {
    console.warn(`  WARNING: image not found, skipping — ${absPath}`);
    continue;
  }
  const buffer = fs.readFileSync(absPath);
  const b64 = buffer.toString('base64');
  images[entry.key] = `data:image/png;base64,${b64}`;
}

// ── Strip path fields from findings data ──────────────────────────────────
function stripPaths(arr) {
  if (!Array.isArray(arr)) return arr;
  return arr.map(item => {
    const { path: _path, ...rest } = item;
    return rest;
  });
}

const cleanData = {
  ...findingsData,
  boardScreenshots: stripPaths(findingsData.boardScreenshots),
  appFrames: stripPaths(findingsData.appFrames),
  inventoryFrames: stripPaths(findingsData.inventoryFrames || []),
};

// ── Build header ───────────────────────────────────────────────────────────
const header = [
  '// AUTO-GENERATED by build.js — do not edit manually',
  '// Run `node build.js` to regenerate',
  '',
  `const FINDINGS_DATA = ${JSON.stringify(cleanData, null, 2)};`,
  '',
  `const IMAGES = ${JSON.stringify(images, null, 2)};`,
  '',
].join('\n');

// ── Write code.js ──────────────────────────────────────────────────────────
const output = header + '\n' + templateSource;
const outputPath = path.join(__dirname, 'code.js');
fs.writeFileSync(outputPath, output, 'utf8');

const sizeKB = (Buffer.byteLength(output, 'utf8') / 1024).toFixed(1);
console.log(`\nWrote code.js — ${sizeKB} KB`);
